<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SkillLearning.Workers.EmailSender-05923a31-15dc-486a-8d20-8a07ceaa5ca8</UserSecretsId>
    <PublishReadyToRun>true</PublishReadyToRun>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>$(MSBuildProjectDirectory)\..\..</DockerfileContext>
    <DockerfileFile>Build\Dockerfile.Workers.EmailSender</DockerfileFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkillLearning.Application\SkillLearning.Application.csproj" />
    <ProjectReference Include="..\SkillLearning.Infrastructure\SkillLearning.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="ReferenceTrimmer" Version="3.3.12" />
  </ItemGroup>
</Project>
